version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directory: "/.github/actions/tailnet/terraform"
    schedule:
      interval: weekly
      day: monday
    groups:
      terraform-tailnet:
        patterns:
          - "*"
