name: 'Setup Go Environment'
description: 'Setup Go environment with checkout and Go installation'
inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: 'stable'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true