# Reusable Go Checks workflow
# This workflow performs comprehensive Go code quality checks including vet, static analysis, linting, vulnerability checks, and security checks

name: Go Checks

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        type: string
        default: 'stable'
      working-directory:
        description: 'Working directory for the Go project'
        required: false
        type: string
        default: '.'
    secrets:
      github-token:
        description: 'GitHub token for accessing private repositories'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Vet:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: densestvoid/workflows/.github/actions/setup@main
      with:
        go-version: ${{ inputs.go-version }}
        
    - name: Vet
      run: go vet ./...
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: false
      
  Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: densestvoid/workflows/.github/actions/setup@main
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install staticcheck
      uses: densestvoid/workflows/.github/actions/install-tool@main
      with:
        tool-package: honnef.co/go/tools/cmd/staticcheck

    - name: Static analysis
      run: staticcheck ./...
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: false

  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: densestvoid/workflows/.github/actions/setup@main
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install golangci-lint
      uses: densestvoid/workflows/.github/actions/install-tool@main
      with:
        tool-package: github.com/golangci/golangci-lint/cmd/golangci-lint

    - name: Lint
      run: golangci-lint run ./...
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: false

  Vulnerability-Check:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: densestvoid/workflows/.github/actions/setup@main
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install govulncheck
      uses: densestvoid/workflows/.github/actions/install-tool@main
      with:
        tool-package: golang.org/x/vuln/cmd/govulncheck

    - name: Vulnerability check
      run: govulncheck ./...
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: false

  Security-Check:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: densestvoid/workflows/.github/actions/setup@main
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install gosec
      uses: densestvoid/workflows/.github/actions/install-tool@main
      with:
        tool-package: github.com/securego/gosec/v2/cmd/gosec

    - name: Security check
      run: gosec ./...
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: false
